# Generated by Django 5.1.5 on 2025-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "company_code",
                    models.CharField(max_length=16, verbose_name="Company Code"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=32, verbose_name="Company Name"),
                ),
                ("stock_price", models.FloatField(verbose_name="Stock Price")),
            ],
            options={
                "verbose_name": "Stock Price Record",
                "verbose_name_plural": "Stock Price Records",
                "ordering": ["company_code", "-date"],
                "unique_together": {("date", "company_code")},
            },
        ),
    ]
